use std::fs;
use std::path::PathBuf;
use anyhow::Result;
use crate::config::Config;

pub fn init_project(path: &PathBuf) -> Result<()> {
    fs::create_dir_all(path.join("assets"))?;
    fs::create_dir_all(path.join("v1.0.0"))?;
    fs::create_dir_all(path.join("search-index"))?;

    let config = Config::default();
    let config_yaml = serde_yaml::to_string(&config)?;
    fs::write(path.join("config.yml"), config_yaml)?;

    let default_md = r#"# Home

Welcome to your documentation site!

This project was generated by **verdocs**.

### 1. Admonition Blocks
Use `type="admonition"` to create prominent callout blocks:

{TIP type="admonition" title="Pro Tip"} 
This is a block-level tip to help you get started.
{/TIP}

{IMPORTANT type="admonition" title="Configuration Required"}
Don't forget to configure your `config.yml`.
{/IMPORTANT}

### 2. Inline Styles
You can also use the same tags for {NOTE}inline highlights{/NOTE} within your paragraphs. For example, you can emphasize {ERROR}critical errors{/ERROR} or {WARN}potential warnings{/WARN} without breaking the flow of your text.

Modify this file or add new ones in the versioned folders to build your documentation.
"#;
    fs::write(path.join("v1.0.0").join("home.md"), default_md)?;

    Ok(())
}
